# Generated by Django 3.2.12 on 2022-04-04 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Baseuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('maxcontent', models.IntegerField(blank=True, null=True)),
                ('dailycontentmarked', models.IntegerField(blank=True, null=True)),
                ('maxmet', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'baseuser',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('user_role', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=500)),
                ('identifier', models.CharField(max_length=300)),
                ('reason', models.CharField(max_length=300)),
                ('placeholder', models.CharField(max_length=300)),
                ('isblocked', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'moderator',
            },
        ),
        migrations.CreateModel(
            name='Priviligeduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'priviligeduser',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('user_role', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=500)),
                ('identifier', models.CharField(max_length=300)),
                ('reason', models.CharField(max_length=300)),
                ('placeholder', models.CharField(max_length=300)),
                ('isresolved', models.BooleanField(blank=True, null=True)),
                ('baseuserid', models.ForeignKey(blank=True, db_column='baseuserid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.baseuser')),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='Reportrequest',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('baseuserid', models.CharField(blank=True, max_length=30, null=True)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('user_role', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=500)),
                ('identifier', models.CharField(max_length=300)),
                ('reason', models.CharField(max_length=300)),
                ('placeholder', models.CharField(max_length=300)),
                ('isresolved', models.BooleanField(blank=True, null=True)),
                ('c', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.content')),
                ('priviligeduserid', models.ForeignKey(blank=True, db_column='priviligeduserid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.priviligeduser')),
            ],
            options={
                'db_table': 'reportrequest',
            },
        ),
        migrations.CreateModel(
            name='Createrequest',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('baseuserid', models.CharField(blank=True, max_length=30, null=True)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('user_role', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=500)),
                ('identifier', models.CharField(max_length=300)),
                ('reason', models.CharField(max_length=300)),
                ('placeholder', models.CharField(max_length=300)),
                ('isresolved', models.BooleanField(blank=True, null=True)),
                ('priviligeduserid', models.ForeignKey(blank=True, db_column='priviligeduserid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.priviligeduser')),
            ],
            options={
                'db_table': 'createrequest',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='create_r',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.createrequest'),
        ),
        migrations.AddField(
            model_name='content',
            name='priviligeduserid',
            field=models.ForeignKey(blank=True, db_column='priviligeduserid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.priviligeduser'),
        ),
    ]
